### ISSUE TITLE
It would be better to note that raftdb is inspired by https://github.com/otoolep/hraftd or forked from hraftd

### ISSUE THREAD

**Issue by chengshiwen** [hanj4096/raftdb#1]
It would be better to note that [raftdb](https://github.com/hanj4096/raftdb) is inspired by https://github.com/otoolep/hraftd or forked from [https://github.com/otoolep/hraftd](https://github.com/otoolep/hraftd)

After all, based on [https://github.com/otoolep/hraftd](https://github.com/otoolep/hraftd), there are not many code modifications in [raftdb](https://github.com/hanj4096/raftdb).

**Comment by hanj4096** [comment]
Thanks for reminding. I will add the note on README, not just on LICENSE_OF_DEPENDENCIES.md.
