### ISSUE TITLE
All `store.ErrNotLeader` should be replaced with `raft.ErrNotLeader`

### ISSUE THREAD

**Issue by chengshiwen** [hanj4096/raftdb#2]
`store.Join` maybe return `raft.ErrNotLeader`, so `store.ErrNotLeader` shouldn't be used, and all `store.ErrNotLeader` should be replaced with `raft.ErrNotLeader`

https://github.com/hanj4096/raftdb/blob/d69b74724bb04cf2057f2cbafdff7841ef44329d/http/service.go#L133-L136

**Comment by hanj4096** [comment]
fiexed
